insert into public.creators (
  id,
  name,
  handle,
  x_avatar_url,
  x_bio,
  x_followers,
  x_following,
  x_tweet_count,
  x_location,
  x_verified,
  x_collected_at,
  x_pinned_tweet,
  x_notable_followers,
  bio,
  region,
  categories,
  skill_type,
  video_styles,
  min_rate,
  max_rate,
  availability,
  contact,
  example,
  sorsa_score,
  verified_campaign,
  portfolio
)
values
  (
    '10000000-0000-4000-8000-000000000001',
    'Onyx Alpha',
    'onyxalpha',
    '',
    '',
    0,
    0,
    0,
    '',
    false,
    null,
    '',
    '',
    'Sharp DeFi explainers, trading app walkthroughs, and launch threads for active crypto audiences.',
    'Global',
    array['DeFi', 'Trading'],
    'Both',
    array['Storytelling', 'Talking Head'],
    450,
    500,
    'Available now',
    'Telegram: @onyxalpha',
    'DeFi launch thread and product walkthrough',
    86,
    false,
    '[]'::jsonb
  ),
  (
    '10000000-0000-4000-8000-000000000002',
    'ChainMuse',
    'chainmuse',
    '',
    '',
    0,
    0,
    0,
    '',
    false,
    null,
    '',
    '',
    'Visual-first NFT and gaming content with strong community engagement across X and short-form video.',
    'Europe',
    array['NFTs', 'GameFi'],
    'Video',
    array['Motion Graphics', 'Storytelling'],
    250,
    300,
    'Available this week',
    'Email: hello@chainmuse.xyz',
    'NFT collection reveal and GameFi trailer breakdown',
    78,
    false,
    '[]'::jsonb
  ),
  (
    '10000000-0000-4000-8000-000000000003',
    'DropWatch Daily',
    'dropwatch',
    '',
    '',
    0,
    0,
    0,
    '',
    false,
    null,
    '',
    '',
    'Simple explainers and step-by-step airdrop guides for users who love practical crypto opportunities.',
    'Africa',
    array['Airdrops', 'Education'],
    'Writing',
    array[]::text[],
    150,
    200,
    'Available now',
    'Telegram: @dropwatchops',
    'Airdrop education thread with simple wallet steps',
    72,
    false,
    '[]'::jsonb
  ),
  (
    '10000000-0000-4000-8000-000000000004',
    'MemeLedger',
    'memeledger',
    '',
    '',
    0,
    0,
    0,
    '',
    false,
    null,
    '',
    '',
    'High-energy meme coin commentary, community raids, and viral launch-day campaign content.',
    'Nigeria',
    array['Memecoins', 'Community Growth'],
    'Both',
    array['Storytelling', 'Talking Head'],
    1450,
    1500,
    'Premium only',
    'WhatsApp: +234 000 000 0000',
    'Memecoin community raid and launch-day content sprint',
    91,
    false,
    '[]'::jsonb
  )
on conflict (id) do update set
  name = excluded.name,
  handle = excluded.handle,
  x_avatar_url = excluded.x_avatar_url,
  x_bio = excluded.x_bio,
  x_followers = excluded.x_followers,
  x_following = excluded.x_following,
  x_tweet_count = excluded.x_tweet_count,
  x_location = excluded.x_location,
  x_verified = excluded.x_verified,
  x_collected_at = excluded.x_collected_at,
  x_pinned_tweet = excluded.x_pinned_tweet,
  x_notable_followers = excluded.x_notable_followers,
  bio = excluded.bio,
  region = excluded.region,
  categories = excluded.categories,
  skill_type = excluded.skill_type,
  video_styles = excluded.video_styles,
  min_rate = excluded.min_rate,
  max_rate = excluded.max_rate,
  availability = excluded.availability,
  contact = excluded.contact,
  example = excluded.example,
  sorsa_score = excluded.sorsa_score,
  verified_campaign = excluded.verified_campaign,
  portfolio = excluded.portfolio,
  updated_at = now();
